### ISSUE TITLE
Publishing to an Ghost CMS URL.

### ISSUE THREAD

**Issue by randrums** [yiglas/obsidian-blog-publisher#1]
Hello. This appears to be the only plugin that may potentially work with Publishing to a Ghost Blog. I wanted to see if I'm doing this correctly. I have attached a screenshot of the Ghost CMS API URL that the Ghost platform provides to me. I entered this into the Obsidian File Publisher fields, but when I try to publish it using the Front matter that is suggested, I just get a "failed to publish error". Do you think there is any way this will work with Obsidian? thank you.
![Screenshot from 2023-05-07 11-36-25](https://user-images.githubusercontent.com/73252280/236687552-0d07cbc0-6f46-4e28-ae8f-2dc4187f9186.png)

**Comment by yiglas** [comment]
Can you please provide the error. 

To see the error go to View -> Toggle Developer Tools 

Then execute the action again.  The console should contain a more in depth log of what is happening.

**Comment by ghost** [comment]
the same thing but for Medium. 
Error: 

Access to XMLHttpRequest at 'https://medium.com/new-story' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by randrums** [comment]
the console gives me this info:
ugin:file-publisher:8606 AxiosError
notify @ plugin:file-publisher:8606
randyhanley.com/:1     Failed to load resource: net::ERR_FAILED
app.js:1 TypeError: Cannot read properties of undefined (reading 'editor')
    at ListLinesViewPluginValue.waitForEditor (plugin:obsidian-outliner:1069:71)
    at new ListLinesViewPluginValue (plugin:obsidian-outliner:1119:14)
    at e.eval [as create] (plugin:obsidian-outliner:1296:82)
    at e.update (app.js:1:396196)
    at e.setState (app.js:1:489535)
    at t.clear (app.js:1:1281516)
    at t [as constructor] (app.js:1:1278518)
    at new t (app.js:1:2004688)
    at new t (app.js:1:2006752)
    at app.js:1:1727162
Ga @ app.js:1
plugin:file-publisher:8573 Publishing file...
index.html:1 Access to XMLHttpRequest at 'https://randyhanley.com/' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ghost** [comment]
I think that Medium allows API use for a few applications only. The rest can't utilize it. 
https://help.medium.com/hc/en-us/articles/213480228-Get-an-integration-token-for-your-writing-app
